# Generated by Django 3.2 on 2026-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=250, null=True)),
                ('output', models.CharField(max_length=250, null=True)),
                ('score', models.IntegerField()),
                ('session_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
