# Generated by Django 3.2 on 2026-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsdetails',
            old_name='output',
            new_name='correct_answer',
        ),
        migrations.AddField(
            model_name='testsdetails',
            name='selected_answer',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
