# Generated by Django 3.2 on 2026-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdetails', '0002_auto_20260715_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsdetails',
            old_name='correct_answer',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='testsdetails',
            name='input',
        ),
        migrations.RemoveField(
            model_name='testsdetails',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testsdetails',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='testsdetails',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testsdetails',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
    ]
