# Generated by Django 3.2 on 2026-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdetails', '0003_auto_20260716_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsdetails',
            name='session_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
