# Generated by Django 3.2 on 2026-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdetails', '0004_alter_testsdetails_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsdetails',
            name='session_date',
            field=models.DateField(null=True),
        ),
    ]
