# Generated by Django 3.2 on 2026-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDetailsFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('session_date', models.DateTimeField(null=True)),
                ('con_audio', models.URLField(max_length=250, null=True)),
            ],
        ),
    ]
