# Generated by Django 3.2 on 2026-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdetails',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
