# Generated by Django 3.2 on 2026-07-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningdetails', '0002_learningdetails_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdetails',
            name='con_audio',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
