# Generated by Django 3.2 on 2026-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningdetails', '0003_learningdetails_con_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningdetails',
            name='session_date',
            field=models.DateTimeField(null=True),
        ),
    ]
