# Generated by Django 3.2 on 2026-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('total_questions', models.IntegerField(null=True)),
                ('total_score', models.IntegerField(null=True)),
                ('session_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
