# Generated by Django 3.2 on 2026-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='session_date',
            field=models.DateField(null=True),
        ),
    ]
